version: '3'

services:
  web:
    build: .
    restart: always
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.swingometer-wcs-life.rule=Host(`swingometer.wcs.life`)
      - traefik.http.routers.swingometer-wcs-life.entrypoints=websecure
      - traefik.http.routers.swingometer-wcs-life.tls.options=default
      - traefik.http.routers.swingometer-wcs-life.tls.certresolver=le
      - traefik.http.routers.swingometer-wcs-life.middlewares=securityHeaders@file

networks:
  web:
    external: true
