version: '3'

services:
  web:
    image: swingometer
    restart: always
    networks:
      web:
        aliases:
        - swingometer_web
    labels:
      - traefik.enable=true
      - traefik.backend=swingometer_web
      - traefik.port=80
      - traefik.frontend.entryPoints=https
      - traefik.frontend.rule=Host:swingometer.wcs.life

networks:
  web:
    external: true
